// This file is generated by generate-std.joke script. Do not edit manually!

package sqlite

import (
	. "github.com/candid82/joker/core"
)

var sqliteNamespace = GLOBAL_ENV.EnsureNamespace(MakeSymbol("joker.sqlite"))



func init() {

	sqliteNamespace.ResetMeta(MakeMeta(nil, "Accesses SQLite databases", "1.0"))

	
}
